### ISSUE TITLE
updateAppMessageShareData接口不能用

### ISSUE THREAD

**Issue by dhb52** [zhetengbiji/jweixin-module#1]
微信调试提示：updateAppMessageShareData:没有此SDK或暂不支持此SDK模拟"

**Comment by zhetengbiji** [comment]
> 微信调试提示：updateAppMessageShareData:没有此SDK或暂不支持此SDK模拟"

说具体点

**Comment by name327** [comment]
jweixin.config({
						debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
						appId: '', // 必填，公众号的唯一标识
						timestamp: json.t.timestamp, // 必填，生成签名的时间戳
						nonceStr: json.t.nonceStr, // 必填，生成签名的随机串
						signature: json.t.signature, // 必填，签名
						jsApiList: ['updateAppMessageShareData'] // 必填，需要使用的JS接口列表
					})



这里是ok



				jweixin.ready(function() { //需在用户可能点击分享按钮前就先调用
					jweixin.updateAppMessageShareData({
						title: '测试标题', // 分享标题
						desc: '说明', // 分享描述
						link: 'http://192.168.31.105:1236/test?id=2', // 分享链接，该链接域名或路径必须与当前页面对应的公众号JS安全域名一致
						imgUrl: 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1558702551523&di=d87e962cf6e4c4ca1c2cdfe604c4f8d5&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fq_70%2Cc_zoom%2Cw_640%2Fimages%2F20190216%2F7405d11be007468c9ea31814d18c224a.jpeg', // 分享图标
						success: function() {
							// 设置成功
						}
					})
				});

这里出错


![WechatIMG28](https://user-images.githubusercontent.com/3320896/58378345-ac260080-7fc4-11e9-915d-f96da520437e.jpeg)

**Comment by zhetengbiji** [comment]
1.6 即可
