### ISSUE TITLE
js1.4的无法自定义分享到微信好友与朋友圈功能

### ISSUE THREAD

**Issue by mobility2015** [zhetengbiji/jweixin-module#4]
请教如题，谢谢。

**Comment by zhetengbiji** [comment]
> 请教如题，谢谢。

是需要更新吗？

**Comment by zhetengbiji** [comment]
已更新到 1.6.0

**Comment by mengerzhuanyong** [comment]
"config:fail,Error: System error, error code:63002,invalid signature [20200205 18:43:18][]"
一直报签名错误是什么原因啊！
不放在uniapp里直接用就是可以的
@zhetengbiji
